### ISSUE TITLE
Please add installation topic inside readme

### ISSUE THREAD

**Issue by lelonco** [fireplusteam/ios-swift-for-vs-code#1]
Please, add the installation guide inside README

**Comment by fireplusteam** [comment]
@lelonco , yes this's a bit missed in readme. Will Add it,
For the time being, you can do it by having `pyinstaller`, `npm` and `vsce` installed. You can do it via homebrew and python pip. then all you need to do is to run `./make.sh` script in the terminal when you are in the root folder of the extension and it should build and install the extension automatically

**Comment by fireplusteam** [comment]
@lelonco , updated readme
let me know if it works for you or if you have experienced any trouble.

**Comment by lelonco** [comment]
@fireplusteam, sorry for the late response. I have an errors with installation 

<details>

<summary>Log</summary>

```
found 0 vulnerabilities
npm notice 
npm notice New patch version of npm available! 10.5.0 -> 10.5.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.2
npm notice Run npm install -g npm@10.5.2 to update!
npm notice 

> vscode-ios@0.0.1 compile
> tsc -p ./

node_modules/@types/vscode/index.d.ts:17742:15 - error TS2300: Duplicate identifier 'FileCoverage'.

17742  export class FileCoverage {
                    ~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:69:18
    69     export class FileCoverage {
                        ~~~~~~~~~~~~
    'FileCoverage' was also declared here.

node_modules/@types/vscode/index.d.ts:17792:15 - error TS2300: Duplicate identifier 'StatementCoverage'.

17792  export class StatementCoverage {
                    ~~~~~~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:124:18
    124     export class StatementCoverage {
                         ~~~~~~~~~~~~~~~~~
    'StatementCoverage' was also declared here.

node_modules/@types/vscode/index.d.ts:17825:15 - error TS2300: Duplicate identifier 'BranchCoverage'.

17825  export class BranchCoverage {
                    ~~~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:155:18
    155     export class BranchCoverage {
                         ~~~~~~~~~~~~~~
    'BranchCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:69:18 - error TS2300: Duplicate identifier 'FileCoverage'.

69     export class FileCoverage {
                    ~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17742:15
    17742  export class FileCoverage {
                        ~~~~~~~~~~~~
    'FileCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:124:18 - error TS2300: Duplicate identifier 'StatementCoverage'.

124     export class StatementCoverage {
                     ~~~~~~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17792:15
    17792  export class StatementCoverage {
                        ~~~~~~~~~~~~~~~~~
    'StatementCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:155:18 - error TS2300: Duplicate identifier 'BranchCoverage'.

155     export class BranchCoverage {
                     ~~~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17825:15
    17825  export class BranchCoverage {
                        ~~~~~~~~~~~~~~
    'BranchCoverage' was also declared here.


Found 6 errors in 2 files.

Errors  Files
     3  node_modules/@types/vscode/index.d.ts:17742
     3  vscode.proposed.testCoverage.d.ts:69
./make.sh: line 8: vsce: command not found
./make.sh: line 10: code: command not found
```
</details>
Could I get these errors because of using Python venv?

**Comment by fireplusteam** [comment]
@lelonco , updated readme file with extra steps and removed the proposal API
you need also to install `vsce` and enable vs code via Terminal which is done via vs code command.

**Comment by lelonco** [comment]
@fireplusteam , still has errors, I think it doesn't compile sources 
<details>
<summary>LOG</summary>

```
88 INFO: PyInstaller: 6.5.0, contrib hooks: 2024.3
88 INFO: Python: 3.12.2
97 INFO: Platform: macOS-14.1.1-arm64-arm-64bit
98 INFO: wrote /Users/yaroslav/ios_vs_code/XCBBuildService.spec
101 INFO: Extending PYTHONPATH with paths
['/Users/yaroslav/ios_vs_code/src/XCBBuildServiceProxy']
158 INFO: checking Analysis
163 INFO: checking PYZ
164 INFO: EXE target arch: arm64
164 INFO: Code signing identity: None
167 INFO: checking PKG
167 INFO: Bootloader /Users/yaroslav/ios_vs_code/env/lib/python3.12/site-packages/PyInstaller/bootloader/Darwin-64bit/run
167 INFO: checking EXE

up to date, audited 245 packages in 538ms

57 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> vscode-ios@0.0.1 compile
> tsc -p ./

node_modules/@types/vscode/index.d.ts:17742:15 - error TS2300: Duplicate identifier 'FileCoverage'.

17742  export class FileCoverage {
                    ~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:69:18
    69     export class FileCoverage {
                        ~~~~~~~~~~~~
    'FileCoverage' was also declared here.

node_modules/@types/vscode/index.d.ts:17792:15 - error TS2300: Duplicate identifier 'StatementCoverage'.

17792  export class StatementCoverage {
                    ~~~~~~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:124:18
    124     export class StatementCoverage {
                         ~~~~~~~~~~~~~~~~~
    'StatementCoverage' was also declared here.

node_modules/@types/vscode/index.d.ts:17825:15 - error TS2300: Duplicate identifier 'BranchCoverage'.

17825  export class BranchCoverage {
                    ~~~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:155:18
    155     export class BranchCoverage {
                         ~~~~~~~~~~~~~~
    'BranchCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:69:18 - error TS2300: Duplicate identifier 'FileCoverage'.

69     export class FileCoverage {
                    ~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17742:15
    17742  export class FileCoverage {
                        ~~~~~~~~~~~~
    'FileCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:124:18 - error TS2300: Duplicate identifier 'StatementCoverage'.

124     export class StatementCoverage {
                     ~~~~~~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17792:15
    17792  export class StatementCoverage {
                        ~~~~~~~~~~~~~~~~~
    'StatementCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:155:18 - error TS2300: Duplicate identifier 'BranchCoverage'.

155     export class BranchCoverage {
                     ~~~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17825:15
    17825  export class BranchCoverage {
                        ~~~~~~~~~~~~~~
    'BranchCoverage' was also declared here.


Found 6 errors in 2 files.

Errors  Files
     3  node_modules/@types/vscode/index.d.ts:17742
     3  vscode.proposed.testCoverage.d.ts:69
(node:60678) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-ios@0.0.1 vscode:prepublish
> npm run compile


> vscode-ios@0.0.1 compile
> tsc -p ./

node_modules/@types/vscode/index.d.ts:17742:15 - error TS2300: Duplicate identifier 'FileCoverage'.

17742  export class FileCoverage {
                    ~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:69:18
    69     export class FileCoverage {
                        ~~~~~~~~~~~~
    'FileCoverage' was also declared here.

node_modules/@types/vscode/index.d.ts:17792:15 - error TS2300: Duplicate identifier 'StatementCoverage'.

17792  export class StatementCoverage {
                    ~~~~~~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:124:18
    124     export class StatementCoverage {
                         ~~~~~~~~~~~~~~~~~
    'StatementCoverage' was also declared here.

node_modules/@types/vscode/index.d.ts:17825:15 - error TS2300: Duplicate identifier 'BranchCoverage'.

17825  export class BranchCoverage {
                    ~~~~~~~~~~~~~~

  vscode.proposed.testCoverage.d.ts:155:18
    155     export class BranchCoverage {
                         ~~~~~~~~~~~~~~
    'BranchCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:69:18 - error TS2300: Duplicate identifier 'FileCoverage'.

69     export class FileCoverage {
                    ~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17742:15
    17742  export class FileCoverage {
                        ~~~~~~~~~~~~
    'FileCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:124:18 - error TS2300: Duplicate identifier 'StatementCoverage'.

124     export class StatementCoverage {
                     ~~~~~~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17792:15
    17792  export class StatementCoverage {
                        ~~~~~~~~~~~~~~~~~
    'StatementCoverage' was also declared here.

vscode.proposed.testCoverage.d.ts:155:18 - error TS2300: Duplicate identifier 'BranchCoverage'.

155     export class BranchCoverage {
                     ~~~~~~~~~~~~~~

  node_modules/@types/vscode/index.d.ts:17825:15
    17825  export class BranchCoverage {
                        ~~~~~~~~~~~~~~
    'BranchCoverage' was also declared here.


Found 6 errors in 2 files.

Errors  Files
     3  node_modules/@types/vscode/index.d.ts:17742
     3  vscode.proposed.testCoverage.d.ts:69
 ERROR  npm failed with exit code 2
Installing extensions...
a [Error]: ENOENT: no such file or directory, open '/Users/yaroslav/ios_vs_code/vscode-ios-0.0.1.vsix'
    at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:18:13405)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:18:14842
    at /Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/yauzl/index.js:37:21
    at FSReqCallback.oncomplete (node:fs:202:23) {
  type: undefined,
  cause: [Error: ENOENT: no such file or directory, open '/Users/yaroslav/ios_vs_code/vscode-ios-0.0.1.vsix'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/Users/yaroslav/ios_vs_code/vscode-ios-0.0.1.vsix'
  }
}
Failed Installing Extensions: file:///Users/yaroslav/ios_vs_code/vscode-ios-0.0.1.vsix
```
</details>

**Comment by fireplusteam** [comment]
@lelonco , did you updated to the latest commit ? I pushed the changes too after deleted proposed API

**Comment by lelonco** [comment]
My bad :D Thank you for your help
